import { useEffect,useState } from 'react'
import { RichTextEditor,RichTextView } from './RichText'
import { readRichText } from '../shared/rich-text'
import type { RichDocument } from '../shared/rich-text'
type Note={id:string;title:string;body:string;body_doc_json?:string|null;kind:string;decision_state?:string|null;decision_outcome?:string|null;decision_contact?:string|null;superseded_reason?:string|null;source_url:string;visibility:string;version:number;archived_at:string|null;engagement_id:string;created_at:string;updated_at:string}
type Link={id:string;title:string;visibility:string;archived_at:string|null;engagement_id?:string}
type Revision={revision_number:number;body_json:string;created_at:string}
type Detail={note:Note;links:Link[];revisions?:Revision[]}
const decisionStates={awaiting:'Awaiting decision',decided:'Decided',superseded:'Superseded'}
const decisionLabel=(n:Note)=>n.decision_state?decisionStates[n.decision_state as keyof typeof decisionStates]:n.kind==='agreed_decision'?'Decided':kinds[n.kind as keyof typeof kinds]
const kinds={strategy:'Strategy note',reported_fact:'Reported fact',hypothesis:'Hypothesis',proposed_action:'Proposed action',agreed_decision:'Agreed decision'}
export function Notes({workspaceId,role,workstream,preview=false,onDirtyChange}:{workspaceId:string;role:string;workstream?:{id:string;engagement_id:string;archived_at:string|null};preview?:boolean;onDirtyChange?:(dirty:boolean)=>void}) {
  const [decisionState,setDecisionState]=useState('awaiting'),[outcome,setOutcome]=useState(''),[contact,setContact]=useState(''),[supersededReason,setSupersededReason]=useState(''),[stateFilter,setStateFilter]=useState('')
  const [hasMore,setHasMore]=useState(false)
  const [notes,setNotes]=useState<Note[]>([]),[streams,setStreams]=useState<Link[]>([]),[engagements,setEngagements]=useState<{id:string;title:string}[]>([])
  const [detail,setDetail]=useState<Detail|null>(null),[creating,setCreating]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false)
  const [query,setQuery]=useState(''),[archived,setArchived]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[kind,setKind]=useState('strategy'),[source,setSource]=useState(''),[links,setLinks]=useState<string[]>([]),[engagement,setEngagement]=useState('')
  const [bodyDoc,setBodyDoc]=useState<RichDocument|null>(null)
  const [conflict,setConflict]=useState(false),[latest,setLatest]=useState<Detail|null>(null)
  const [sharing,setSharing]=useState<Detail|null>(null),[revision,setRevision]=useState<Revision|null>(null)
  const base=`/api/workspaces/${workspaceId}`,owner=role==='owner'&&!preview,decision=!!workstream,Heading=decision?'h2':'h1'
  const workflow=decision||!!detail?.note.decision_state||detail?.note.kind==='agreed_decision'||creating&&kind==='agreed_decision'
  const workflowData={decisionState,decisionOutcome:outcome,decisionContact:contact,supersededReason}
  const words=(value:string)=>decision?value.replace(/Notes/g,'Decisions').replace(/notes/g,'decisions').replace(/Note/g,'Decision').replace(/note/g,'decision'):value
  const listPath=`${workstream?`/workstreams/${workstream.id}/decisions`:'/notes'}?archived=${archived?1:0}&q=${encodeURIComponent(query)}${preview?'&preview=1':''}${decision?`&state=${stateFilter}`:''}`
  const detailPath=(id:string)=>`/notes/${id}${preview?'?preview=1':''}`
  async function request(path:string,method='GET',data?:object){const r=await fetch(base+path,{method,...(data?{headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{})});const value=await r.json();if(!r.ok)throw Object.assign(new Error(value.error??'Unable to save note.'),{status:r.status});return value}
  async function load(){const d=await request(listPath);setNotes(d.notes);setHasMore(!!d.hasMore)}
  useEffect(()=>{let active=true;request(listPath).then(d=>{if(active){setNotes(d.notes);setHasMore(!!d.hasMore)}}).catch(e=>{if(active)setMessage(e.message)});return()=>{active=false}},[workspaceId,query,archived,workstream?.id,preview,stateFilter])
  useEffect(()=>{request(`/workstreams${preview?'?preview=1':''}`).then(d=>setStreams(d.workstreams)).catch(e=>setMessage(e.message));request('/engagements').then(d=>{setEngagements(d.engagements);setEngagement(workstream?.engagement_id??d.engagements[0]?.id??'')}).catch(e=>setMessage(e.message))},[workspaceId])
  useEffect(()=>{onDirtyChange?.(dirty);return()=>onDirtyChange?.(false)},[dirty,onDirtyChange])
  useEffect(()=>{if(!dirty||workstream)return;const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};const navigate=(e:Event)=>{if(!window.confirm(words('Discard unsaved note changes?')))e.preventDefault()};addEventListener('beforeunload',unload);addEventListener('portal:navigate',navigate);return()=>{removeEventListener('beforeunload',unload);removeEventListener('portal:navigate',navigate)}},[dirty,workstream])
  function discard(){return !dirty||window.confirm(words('Discard unsaved note changes?'))}
  function hydrate(d:Detail){setDetail(d);setTitle(d.note.title);setBody(d.note.body);setBodyDoc(readRichText(d.note.body_doc_json,d.note.body));setKind(d.note.kind);setDecisionState(d.note.decision_state??'decided');setOutcome(d.note.decision_outcome??'');setContact(d.note.decision_contact??'');setSupersededReason(d.note.superseded_reason??'');setSource(d.note.source_url);setLinks(d.links.map(l=>l.id));setEngagement(d.note.engagement_id);setCreating(false);setDirty(false);setSharing(null);setRevision(null);setConflict(false);setLatest(null)}
  async function open(id:string){if(!discard())return;try{hydrate(await request(detailPath(id)));setMessage('')}catch(e){setMessage((e as Error).message)}}
  async function perform(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();await load()}catch(e){setMessage((e as Error).message);if((e as Error&{status?:number}).status===409)setConflict(true)}finally{setBusy(false)}}
  const editable=!preview&&(!decision||owner)&&!workstream?.archived_at&&role!=='viewer'&&(owner||!workflow)&&!detail?.note.archived_at&&!detail?.links.some(l=>l.archived_at)
  const noteFields=<><label htmlFor="note-title">{words('Note title')}</label><input id="note-title" required maxLength={200} value={title} onChange={e=>{setTitle(e.target.value);setDirty(true)}}/>
    {owner&&workflow&&<>
      <label htmlFor="decision-status">Decision status</label><select id="decision-status" value={decisionState} onChange={e=>{setDecisionState(e.target.value);if(e.target.value!=='superseded')setSupersededReason('');setDirty(true)}}>{Object.entries(decisionStates).map(([value,label])=><option key={value} value={value} disabled={value==='superseded'&&(creating||detail?.note.decision_state==='awaiting')}>{label}</option>)}</select>
      <p>{decisionState==='awaiting'?'Describe the question, options, and what is needed to make the decision.':decisionState==='decided'?'Record the selected direction and why it was chosen.':'Keep the earlier outcome and explain what replaced it.'}</p>
    </>}
    <label htmlFor="note-body">{words('Note text')}</label><RichTextEditor key={`${detail?.note.id??'new'}:${detail?.note.version??0}`} id="note-body" label={words('Note text')} maxLength={20000} value={body} document={bodyDoc} onDirty={()=>setDirty(true)} onChange={(value,doc)=>{setBody(value);setBodyDoc(doc);setDirty(true)}}/>
    {(!workflow||creating&&!decision)&&(owner||creating)&&<><label htmlFor="note-kind">Note type</label><select id="note-kind" value={kind} onChange={e=>{setKind(e.target.value);setDirty(true)}}>{Object.entries(kinds).filter(([k])=>owner||k!=='agreed_decision').map(([k,label])=><option key={k} value={k}>{label}</option>)}</select></>}
    {owner&&workflow&&<>
      <label htmlFor="decision-contact">Decision-maker or contact (optional)</label><input id="decision-contact" maxLength={200} value={contact} onChange={e=>{setContact(e.target.value);setDirty(true)}}/>
      <label htmlFor="decision-outcome">Outcome / selected direction{decisionState==='awaiting'?' (optional until decided)':''}</label><textarea id="decision-outcome" required={decisionState!=='awaiting'} maxLength={4000} value={outcome} onChange={e=>{setOutcome(e.target.value);setDirty(true)}}/>
      {decisionState==='superseded'&&<><label htmlFor="decision-superseded">Reason superseded / replacement decision</label><textarea id="decision-superseded" required maxLength={2000} value={supersededReason} onChange={e=>{setSupersededReason(e.target.value);setDirty(true)}}/></>}
    </>}
    <label htmlFor="note-source">Source URL (optional)</label><input id="note-source" type="url" maxLength={2000} value={source} onChange={e=>{setSource(e.target.value);setDirty(true)}}/>
    {(owner||creating)&&<fieldset><legend>Linked workstreams</legend>{streams.filter(s=>s.engagement_id===engagement).map(s=><label className="inline-check" key={s.id}><input type="checkbox" disabled={decision&&s.id===workstream?.id} checked={links.includes(s.id)} onChange={e=>{setLinks(e.target.checked?[...links,s.id]:links.filter(id=>id!==s.id));setDirty(true)}}/>{s.title} · {s.visibility}</label>)}{!streams.length&&<p>No workstreams yet. You can save a standalone note.</p>}</fieldset>}</>
  return <><Heading>{decision?'Decisions':'Notes'}</Heading><p className="lede">{decision?'Track questions awaiting a decision, record the chosen outcome, and keep superseded decisions with their history.':'Keep strategy, facts, hypotheses, and proposed actions distinct. Notes can link to several workstreams.'}</p>
    <div className="portal-actions">{!preview&&(!decision||owner)&&!workstream?.archived_at&&role!=='viewer'&&<button className="primary-button" onClick={()=>{if(discard()){setDetail(null);setCreating(true);setTitle('');setBody('');setBodyDoc(null);setKind(decision?'proposed_action':'strategy');setDecisionState(decision?'awaiting':'decided');setOutcome('');setContact('');setSupersededReason('');setSource('');setLinks(workstream?[workstream.id]:[]);setDirty(false);setSharing(null);setRevision(null);setConflict(false);setLatest(null)}}}>{words('Add note')}</button>}{owner&&<label className="inline-check"><input type="checkbox" checked={archived} onChange={e=>{if(discard()){setArchived(e.target.checked);setDetail(null);setCreating(false);setDirty(false)}}}/>{words('Include archived notes and parents')}</label>}</div>
    <label htmlFor="note-search">{words('Search notes')}</label><input id="note-search" type="search" value={query} onChange={e=>setQuery(e.target.value)}/>
    {decision&&<><label htmlFor="decision-filter">Filter decision status</label><select id="decision-filter" value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="">All decisions</option>{Object.entries(decisionStates).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></>}
    <div className="portal-columns"><section className="foundation-panel portal-section"><h2>{words('Saved notes')}</h2>{notes.length?<ul className="record-list">{notes.map(n=><li key={n.id}><button className="record-button" onClick={()=>open(n.id)}>{n.title}</button><p>{decisionLabel(n)}{!decision&&` · ${n.visibility}`}{n.archived_at?' · Archived':''}</p></li>)}</ul>:<p>{words('No notes match this view.')}</p>}{hasMore&&<p>Showing the first 100 matching decisions. Refine your search to find more.</p>}</section>
    <div>{conflict&&detail&&<section className="foundation-panel portal-section"><h2>{words('This note changed')}</h2><p>Your unsaved input is retained. Compare the latest saved version before deciding what to keep.</p><button className="outline-button" onClick={()=>perform(async()=>{setLatest(await request(detailPath(detail.note.id)))})}>Compare latest saved version</button>{latest&&<><h3>{words('Latest saved note')}</h3><p>{latest.note.title}</p><DecisionFacts note={latest.note}/><RichTextView value={latest.note.body} document={latest.note.body_doc_json}/><p>{latest.note.source_url}</p><button className="outline-button" onClick={()=>{if(discard())hydrate(latest)}}>Reload latest saved version</button></>}</section>}{creating&&<section className="foundation-panel portal-section"><h2>{decision?'New decision':`New ${owner?'private':'shared'} note`}</h2><form onSubmit={e=>{e.preventDefault();perform(async()=>{const result=await request(workstream?`/workstreams/${workstream.id}/decisions`:'/notes','POST',workstream?{...workflowData,title,body,bodyDoc,sourceUrl:source,workstreamIds:links.filter(id=>id!==workstream.id)}:{...(workflow?workflowData:{}),engagementId:engagement,title,body,bodyDoc,kind,sourceUrl:source,workstreamIds:links,visibility:owner?'private':'shared'});hydrate(await request(detailPath(result.note.id)));setMessage(words('Note created; history retained.'))})}}>{!decision&&<><label htmlFor="note-engagement">Engagement</label><select id="note-engagement" required value={engagement} onChange={e=>{setEngagement(e.target.value);setLinks([])}}>{engagements.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></>}{noteFields}<button className="primary-button" disabled={busy}>{decision?'Create decision':`Create ${owner?'private':'shared'} note`}</button></form></section>}
    {detail&&<><section className="foundation-panel portal-section"><h2>{detail.note.title}</h2><span className="scope-tag">{workflow?decisionLabel(detail.note):`${detail.note.visibility} · ${kinds[detail.note.kind as keyof typeof kinds]}`}{detail.note.archived_at?' · Archived':''}</span><p>{decision?'Recorded':'Created'} {new Date(detail.note.created_at).toLocaleString()} · Updated {new Date(detail.note.updated_at).toLocaleString()}</p>
      {editable?<form onSubmit={e=>{e.preventDefault();perform(async()=>{await request(`/notes/${detail.note.id}`,'PATCH',{version:detail.note.version,title,body,bodyDoc,sourceUrl:source,...(owner?{...(workflow?workflowData:{kind}),workstreamIds:workstream?[...new Set([workstream.id,...links])]:links}:{})});hydrate(await request(detailPath(detail.note.id)));setMessage(words('Note saved; previous version retained.'))})}}>{noteFields}<button className="primary-button" disabled={busy}>{words('Save note')}</button></form>:<><DecisionFacts note={detail.note}/><RichTextView value={detail.note.body} document={detail.note.body_doc_json}/>{detail.note.source_url&&<a className="text-link" href={detail.note.source_url} target="_blank" rel="noopener noreferrer">Open source</a>}<ul>{detail.links.map(l=><li key={l.id}>{l.title}{l.archived_at?' · Archived':''}</li>)}</ul></>}
      {detail.links.some(l=>l.archived_at)&&<p>{words('Restore linked workstreams before editing or restoring this note.')}</p>}
      {owner&&<><div className="portal-actions"><button className="outline-button" disabled={busy||!!detail.note.archived_at&&detail.links.some(l=>l.archived_at)} onClick={()=>{if(discard())perform(async()=>{await request(`/notes/${detail.note.id}`,'PATCH',{version:detail.note.version,archived:!detail.note.archived_at});hydrate(await request(detailPath(detail.note.id)));setMessage(detail.note.archived_at?words('Note restored.'):words('Note archived; history retained.'))})}}>{words(detail.note.archived_at?'Restore note':'Archive note')}</button>
        </div><details><summary>Access settings</summary><p>Visibility: {detail.note.visibility==='private'?'Only you':'Shared with active workspace members'}. This is separate from decision status.</p>{!detail.note.archived_at&&<button className="outline-button" disabled={busy} onClick={()=>{if(discard())perform(async()=>{if(detail.note.visibility==='shared'){await request(`/notes/${detail.note.id}`,'PATCH',{version:detail.note.version,visibility:'private'});hydrate(await request(detailPath(detail.note.id)));setMessage(words('Note is private.'))}else{const d=await request(`/notes/${detail.note.id}/share-preview`);if(!d.shareable)throw new Error('Share and restore all linked workstreams before sharing this note.');setSharing(d)}})}}>{words(detail.note.visibility==='shared'?'Make note private':'Preview note sharing')}</button>}</details></>}
      {sharing&&<aside className="share-preview"><h3>{words('Shared note preview')}</h3><strong>{sharing.note.title}</strong><DecisionFacts note={sharing.note}/><RichTextView value={sharing.note.body} document={sharing.note.body_doc_json}/><p>{decisionLabel(sharing.note)}</p>{sharing.note.source_url&&<p>{sharing.note.source_url}</p>}<ul>{sharing.links.map(l=><li key={l.id}>{l.title}</li>)}</ul><p>Past versions stay private to you.</p><button className="primary-button" disabled={busy} onClick={()=>perform(async()=>{await request(`/notes/${detail.note.id}`,'PATCH',{version:detail.note.version,visibility:'shared'});hydrate(await request(detailPath(detail.note.id)));setMessage(words('Note shared with active members.'))})}>{words('Share this note')}</button></aside>}
    </section>{owner&&<section className="foundation-panel portal-section"><h2>{decision?'Decision history':words('Note history · private')}</h2><ul>{detail.revisions?.map(r=><li key={r.revision_number}><button className="text-button" onClick={()=>setRevision(r)}>View {decision?'decision':'note'} version {r.revision_number}</button><span> · {new Date(r.created_at).toLocaleString()}</span></li>)}</ul>{revision&&<><h3>Version {revision.revision_number} · read only</h3><h4>{JSON.parse(revision.body_json).title}</h4><DecisionFacts snapshot={JSON.parse(revision.body_json)}/><RichTextView value={JSON.parse(revision.body_json).body??''} document={JSON.parse(revision.body_json).bodyDoc}/>{!JSON.parse(revision.body_json).decisionState&&<p>{kinds[JSON.parse(revision.body_json).kind as keyof typeof kinds]}</p>}<p>{JSON.parse(revision.body_json).sourceUrl}</p></>}</section>}</>}
    </div></div>{decision&&(creating||detail)&&<button className="outline-button" onClick={()=>{if(discard()){setDetail(null);setCreating(false);setDirty(false);setSharing(null);setRevision(null);setConflict(false);setLatest(null)}}}>Close decision</button>}<p role="status" aria-live="polite">{message}</p></>
}

function DecisionFacts({note,snapshot}:{note?:Note;snapshot?:{decisionState?:string;decisionOutcome?:string;decisionContact?:string;supersededReason?:string}}) {
  const state=note?.decision_state??snapshot?.decisionState,outcome=note?.decision_outcome??snapshot?.decisionOutcome,contact=note?.decision_contact??snapshot?.decisionContact,reason=note?.superseded_reason??snapshot?.supersededReason
  if(!state&&!outcome&&!contact&&!reason)return null
  return <div className="decision-facts">{state&&<p><strong>Status:</strong> {decisionStates[state as keyof typeof decisionStates]}</p>}{contact&&<p><strong>Decision-maker or contact:</strong> {contact}</p>}{outcome&&<p><strong>{state==='awaiting'?'Previous / proposed outcome:':'Outcome / selected direction:'}</strong> {outcome}</p>}{reason&&<p><strong>Reason superseded:</strong> {reason}</p>}</div>
}
