import { useEffect,useRef,useState } from 'react'
import { Notes } from './Notes'
import { WorkstreamItems } from './WorkstreamItems'
import { RichTextEditor,RichTextView } from './RichText'
import { readRichText } from '../shared/rich-text'
import type { RichDocument } from '../shared/rich-text'
import type { NavigationWorkstream } from './Dashboard'
type Stream={id:string;title:string;purpose:string;purpose_doc_json?:string|null;status:string;visibility:string;version:number;archived_at:string|null;engagement_id:string;priority:number|null;sort_order:number;owner_name:string|null}
type Revision={id:string;revision_number:number;body_json:string;change_summary:string;agreement_state:string;visibility:string;created_at:string}
type Detail={stream:Stream;draft?:{body_json:string;version:number}|null;revisions:Revision[];openTasks?:number}
const fields=[['outcome','Intended outcome'],['included','Included scope'],['excluded','Excluded scope'],['assumptions','Assumptions and hypotheses'],['questions','Open questions'],['successMeasures','Success measures'],['owner','Scope owner or contact'],['targetDate','Optional target date']] as const
const emptyScope=()=>Object.fromEntries(fields.map(([key])=>[key,'']))
function ScopeSnapshot({body}:{body:string}) {
  const saved=JSON.parse(body)
  return <div className="scope-snapshot">{fields.map(([key,label])=><div key={key}><h4>{label}</h4><RichTextView value={Array.isArray(saved[key])?saved[key].join('\n'):String(saved[key]??'')} document={saved.richText?.[key]}/></div>)}</div>
}
export function Workstreams({workspaceId,role,selectedId,onSelectionChange,onStreamsChange}:{workspaceId:string;role:string;selectedId?:string|null;onSelectionChange?:(id:string|null)=>void;onStreamsChange?:(streams:NavigationWorkstream[])=>void}) {
  const [streams,setStreams]=useState<Stream[]>([]),[preview,setPreview]=useState(false),[archived,setArchived]=useState(false)
  const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[detail,setDetail]=useState<Detail|null>(null)
  const [title,setTitle]=useState(''),[purpose,setPurpose]=useState(''),[status,setStatus]=useState('proposed'),[priority,setPriority]=useState(''),[ownerName,setOwnerName]=useState(''),[sortOrder,setSortOrder]=useState(0)
  const [creating,setCreating]=useState(false),[engagements,setEngagements]=useState<{id:string;title:string}[]>([]),[engagementId,setEngagementId]=useState('')
  const [scope,setScope]=useState<Record<string,string>>(emptyScope),[summary,setSummary]=useState(''),[agreement,setAgreement]=useState('proposed'),[source,setSource]=useState(''),[revisionVisibility,setRevisionVisibility]=useState('private'),[selectedRevision,setSelectedRevision]=useState<Revision|null>(null)
  const [sharing,setSharing]=useState<Detail|null>(null),[conflict,setConflict]=useState(false),[latest,setLatest]=useState<Detail|null>(null)
  const [purposeDoc,setPurposeDoc]=useState<RichDocument|null>(null),[scopeDocs,setScopeDocs]=useState<Record<string,RichDocument>>({})
  const [itemDirty,setItemDirty]=useState(false),[decisionDirty,setDecisionDirty]=useState(false)
  const detailHeading=useRef<HTMLHeadingElement>(null)
  const loadedSelection=useRef<{id:string;preview:boolean}|null>(null)
  const base=`/api/workspaces/${workspaceId}`
  async function request(path:string,method='GET',body?:object) {
    const r=await fetch(base+path,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})})
    const data=await r.json();if(!r.ok)throw Object.assign(new Error(data.error??'Unable to save.'),{status:r.status});return data
  }
  async function load(){const d=await request(`/workstreams?archived=${archived?1:0}&preview=${preview?1:0}`);setStreams(d.workstreams);onStreamsChange?.(d.workstreams)}
  function hydrate(d:Detail){loadedSelection.current={id:d.stream.id,preview};setDetail(d);setTitle(d.stream.title);setPurpose(d.stream.purpose);setPurposeDoc(readRichText(d.stream.purpose_doc_json,d.stream.purpose,5000));setStatus(d.stream.status);setPriority(d.stream.priority?.toString()??'');setOwnerName(d.stream.owner_name??'');setSortOrder(d.stream.sort_order);const saved=JSON.parse(d.draft?.body_json??'{}');setScope(Object.fromEntries(fields.map(([key])=>[key,typeof saved[key]==='string'?saved[key]:Array.isArray(saved[key])?saved[key].join('\n'):''])));setScopeDocs(Object.fromEntries(fields.slice(0,6).map(([key])=>[key,readRichText(saved.richText?.[key],typeof saved[key]==='string'?saved[key]:Array.isArray(saved[key])?saved[key].join('\n'):'',4000)])));setDirty(false);setSelectedRevision(null);setSharing(null);setCreating(false);setConflict(false);setLatest(null);onSelectionChange?.(d.stream.id)}
  useEffect(()=>{load().catch(e=>setMessage(e.message));if(role==='owner')request('/engagements').then(d=>{setEngagements(d.engagements);setEngagementId(d.engagements[0]?.id??'')}).catch(e=>setMessage(e.message))},[workspaceId,preview,archived])
  useEffect(()=>{
    if(!onSelectionChange)return
    if(selectedId&&loadedSelection.current?.id===selectedId&&loadedSelection.current.preview===preview)return
    let current=true
    loadedSelection.current=null;setDetail(null);if(selectedId)setCreating(false);setDirty(false);setMessage('')
    if(selectedId)request(`/workstreams/${selectedId}${preview?'?preview=1':''}`).then(d=>{if(current)hydrate(d)}).catch(e=>{if(current)setMessage(e.message)})
    return()=>{current=false}
  },[selectedId,workspaceId,preview])
  useEffect(()=>{if(detail){detailHeading.current?.focus({preventScroll:true});if(matchMedia('(max-width:700px)').matches)detailHeading.current?.scrollIntoView({block:'start'})}},[detail?.stream.id])
  useEffect(()=>{if(!dirty&&!itemDirty&&!decisionDirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};const navigate=(e:Event)=>{if(!window.confirm('Discard unsaved workstream changes?'))e.preventDefault()};addEventListener('portal:navigate',navigate);addEventListener('beforeunload',warn);return()=>{removeEventListener('beforeunload',warn);removeEventListener('portal:navigate',navigate)}},[dirty,itemDirty,decisionDirty])
  function discard(){return !(dirty||itemDirty||decisionDirty)||window.confirm('Discard unsaved workstream changes?')}
  async function open(id:string){if(!discard())return;if(onSelectionChange){onSelectionChange(id);return}setMessage('');try{hydrate(await request(`/workstreams/${id}${preview?'?preview=1':''}`))}catch(e){setMessage((e as Error).message)}}
  async function perform(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();await load()}catch(e){setMessage((e as Error).message);if((e as Error&{status?:number}).status===409)setConflict(true)}finally{setBusy(false)}}
  const owner=role==='owner'&&!preview,editable=!preview&&role!=='viewer'
  return <><h1>Workstreams</h1><p className="lede">Keep scope, open questions, and changes in direction together.</p>
    <div className="portal-actions">{role==='owner'&&<><button className="outline-button" onClick={()=>{if(discard()){onSelectionChange?.(null);setPreview(!preview);setDetail(null);setCreating(false);setDirty(false)}}}>{preview?'Return to owner view':'Preview shared view'}</button>{!preview&&<><button className="primary-button" onClick={()=>{if(discard()){onSelectionChange?.(null);setCreating(true);setDetail(null);setTitle('');setPurpose('');setPurposeDoc(null);setDirty(false)}}}>Add workstream</button><label className="inline-check"><input type="checkbox" checked={archived} onChange={e=>{if(discard()){onSelectionChange?.(null);setArchived(e.target.checked);setDetail(null);setDirty(false)}}}/>Include archived</label></>}</>}
    </div>{preview&&<p className="scope-tag">Shared preview · only content available to shared members</p>}
    <div className={onStreamsChange?'workstream-content':'portal-columns'}>{!onStreamsChange&&<section className="foundation-panel portal-section"><h2>Current workstreams</h2>{streams.length?<ul className="record-list">{streams.map(s=><li key={s.id}><button className="record-button" onClick={()=>open(s.id)}>{s.title}</button><p>{s.visibility==='private'?'Private':'Shared'} · {s.archived_at?'Archived':s.status.replaceAll('_',' ')}</p></li>)}</ul>:<p>No {preview?'shared ':''}workstreams yet.</p>}</section>}
    {onStreamsChange&&!detail&&!creating&&<section className="foundation-panel portal-section"><h2>{message&&selectedId?'Workstream unavailable':selectedId?'Opening workstream…':'Choose a workstream'}</h2><p>{selectedId?'Its saved details will appear here when available.':streams.length?'Select a workstream in the left menu to open its details here.':preview?'No shared workstreams yet.':'Add a workstream to get started.'}</p></section>}
    <div>{conflict&&detail&&<section className="foundation-panel portal-section"><h2>This record changed</h2><p>Your unsaved input is retained. Compare the latest saved version before deciding what to keep.</p><button className="outline-button" onClick={()=>perform(async()=>{setLatest(await request(`/workstreams/${detail.stream.id}`))})}>Compare latest saved version</button>{latest&&<><h3>Latest saved workstream</h3><p>{latest.stream.title}</p><RichTextView value={latest.stream.purpose} document={latest.stream.purpose_doc_json}/>{latest.draft?<ScopeSnapshot body={latest.draft.body_json}/>:<p>No saved draft.</p>}<button className="outline-button" onClick={()=>{if(discard())hydrate(latest)}}>Reload latest saved version</button></>}</section>}{creating&&<section className="foundation-panel portal-section"><h2>New workstream</h2><form onSubmit={e=>{e.preventDefault();perform(async()=>{const s=await request('/workstreams','POST',{engagementId,title,purpose,purposeDoc});hydrate(await request(`/workstreams/${s.id}`));setMessage('Workstream created privately.')})}}>
      <label htmlFor="engagement">Engagement</label><select id="engagement" required value={engagementId} onChange={e=>setEngagementId(e.target.value)}>{engagements.map(i=><option key={i.id} value={i.id}>{i.title}</option>)}</select>
      <label htmlFor="stream-title">Workstream title</label><input id="stream-title" required maxLength={200} value={title} onChange={e=>{setTitle(e.target.value);setDirty(true)}}/>
      <label htmlFor="stream-purpose">Purpose</label><RichTextEditor key="new-purpose" id="stream-purpose" label="Purpose" maxLength={5000} value={purpose} document={purposeDoc} onDirty={()=>setDirty(true)} onChange={(value,doc)=>{setPurpose(value);setPurposeDoc(doc);setDirty(true)}}/>
      <button className="primary-button" disabled={busy}>Create private workstream</button></form></section>}
    {detail&&<><section className="foundation-panel portal-section"><h2 ref={detailHeading} tabIndex={-1}>{detail.stream.title}</h2><span className="scope-tag">{detail.stream.visibility==='private'?'Private':'Shared'}{detail.stream.archived_at?' · Archived':''}</span>
      {editable&&!detail.stream.archived_at?<form onSubmit={e=>{e.preventDefault();perform(async()=>{await request(`/workstreams/${detail.stream.id}`,'PATCH',{version:detail.stream.version,title,purpose,purposeDoc,...(owner?{status,priority:priority?Number(priority):null,ownerName:ownerName||null,sortOrder}:{})});hydrate(await request(`/workstreams/${detail.stream.id}`));setMessage('Workstream saved.')})}}>
        <label htmlFor="edit-title">Workstream title</label><input id="edit-title" value={title} required maxLength={200} onChange={e=>{setTitle(e.target.value);setDirty(true)}}/>
        <label htmlFor="edit-purpose">Purpose</label><RichTextEditor key={`${detail.stream.id}:${detail.stream.version}`} id="edit-purpose" label="Purpose" maxLength={5000} value={purpose} document={purposeDoc} onDirty={()=>setDirty(true)} onChange={(value,doc)=>{setPurpose(value);setPurposeDoc(doc);setDirty(true)}}/>
        {owner&&<><label htmlFor="stream-status">Workstream status</label><select id="stream-status" value={status} onChange={e=>{setStatus(e.target.value);setDirty(true)}}>{['proposed','needs_scoping','active','on_hold','completed'].map(v=><option key={v} value={v}>{v.replaceAll('_',' ')}</option>)}</select>
          <label htmlFor="priority">Priority</label><select id="priority" value={priority} onChange={e=>{setPriority(e.target.value);setDirty(true)}}><option value="">Not set</option>{[1,2,3,4,5].map(v=><option key={v}>{v}</option>)}</select>
          <label htmlFor="stream-owner">Owner or contact</label><input id="stream-owner" value={ownerName} onChange={e=>{setOwnerName(e.target.value);setDirty(true)}}/>
          <label htmlFor="sort-order">Display order</label><input id="sort-order" type="number" min={0} value={sortOrder} onChange={e=>{setSortOrder(Number(e.target.value));setDirty(true)}}/></>}
        <button className="primary-button" disabled={busy}>Save workstream</button></form>:<><RichTextView value={detail.stream.purpose||'Purpose not set.'} document={detail.stream.purpose_doc_json}/><p>{detail.stream.status.replaceAll('_',' ')}</p></>}
      {owner&&<><p>Archiving hides linked records from active views and keeps their history.{detail.openTasks?` This workstream has ${detail.openTasks} open follow-ups.`:''}</p>
        <div className="portal-actions"><button className="outline-button" disabled={busy} onClick={()=>{if(discard())perform(async()=>{await request(`/workstreams/${detail.stream.id}`,'PATCH',{version:detail.stream.version,archived:!detail.stream.archived_at});hydrate(await request(`/workstreams/${detail.stream.id}`));setMessage(detail.stream.archived_at?'Workstream restored.':'Workstream archived. Select Include archived to find it.')})}}>{detail.stream.archived_at?'Restore workstream':'Archive workstream'}</button>
        {!detail.stream.archived_at&&<button className="outline-button" disabled={busy} onClick={()=>{if(discard())perform(async()=>{if(detail.stream.visibility==='shared'){await request(`/workstreams/${detail.stream.id}`,'PATCH',{version:detail.stream.version,visibility:'private'});hydrate(await request(`/workstreams/${detail.stream.id}`));setMessage('Workstream is private.')}else setSharing(await request(`/workstreams/${detail.stream.id}/share-preview`))})}}>{detail.stream.visibility==='shared'?'Make private':'Preview sharing'}</button>}</div>
        {sharing&&<aside className="share-preview"><h3>Shared content preview</h3><p>{sharing.stream.title}</p><RichTextView value={sharing.stream.purpose} document={sharing.stream.purpose_doc_json}/><p>Only explicitly shared scope revisions are included. Your current draft stays private.</p><>{sharing.revisions.map(r=><div key={r.id}><h4>Revision {r.revision_number}: {r.change_summary}</h4><ScopeSnapshot body={r.body_json}/></div>)}</><button className="primary-button" disabled={busy} onClick={()=>perform(async()=>{await request(`/workstreams/${detail.stream.id}`,'PATCH',{version:detail.stream.version,visibility:'shared'});hydrate(await request(`/workstreams/${detail.stream.id}`));setMessage('Workstream shared with active members.')})}>Share this workstream</button></aside>}
      </>}
    </section>
    <WorkstreamItems key={`${detail.stream.id}:${!!detail.stream.archived_at}:${preview}`} workspaceId={workspaceId} workstreamId={detail.stream.id} role={role} preview={preview} parentShared={detail.stream.visibility==='shared'} parentArchived={!!detail.stream.archived_at} onDirtyChange={setItemDirty} onSaved={()=>{request(`/workstreams/${detail.stream.id}`).then(d=>setDetail(current=>current&&current.stream.id===d.stream.id?{...current,openTasks:d.openTasks}:current)).catch(e=>setMessage(e.message))}}/>
    <section className="foundation-panel portal-section workstream-decisions"><Notes key={`${detail.stream.id}:${!!detail.stream.archived_at}:${preview}`} workspaceId={workspaceId} role={role} workstream={detail.stream} preview={preview} onDirtyChange={setDecisionDirty}/></section>
    {owner&&!detail.stream.archived_at&&<section className="foundation-panel portal-section"><h2>Private scope draft</h2><form onSubmit={e=>{e.preventDefault();perform(async()=>{await request(`/workstreams/${detail.stream.id}/draft`,'POST',{version:detail.draft?.version??0,scope:{...scope,richText:scopeDocs}});hydrate(await request(`/workstreams/${detail.stream.id}`));setMessage('Scope draft saved privately.')})}}>{fields.map(([key,label])=><div className="field" key={key}><label htmlFor={`scope-${key}`}>{label}</label>{key==='targetDate'?<input id={`scope-${key}`} type="date" value={scope[key]} onChange={e=>{setScope({...scope,[key]:e.target.value});setDirty(true)}}/>:key==='owner'?<input id={`scope-${key}`} maxLength={4000} value={scope[key]} onChange={e=>{setScope({...scope,[key]:e.target.value});setDirty(true)}}/>:<RichTextEditor key={`${detail.stream.id}:${detail.draft?.version??0}:${key}`} id={`scope-${key}`} label={label} maxLength={4000} value={scope[key]} document={scopeDocs[key]} onDirty={()=>setDirty(true)} onChange={(value,doc)=>{setScope({...scope,[key]:value});setScopeDocs({...scopeDocs,[key]:doc});setDirty(true)}}/>}</div>)}<button className="primary-button" disabled={busy}>Save scope draft</button></form>
      {detail.draft&&<form onSubmit={e=>{e.preventDefault();if(dirty){setMessage('Save your draft before creating a revision.');return}perform(async()=>{await request(`/workstreams/${detail.stream.id}/revisions`,'POST',{version:detail.draft!.version,changeSummary:summary,agreementState:agreement,agreementSource:source,visibility:revisionVisibility});hydrate(await request(`/workstreams/${detail.stream.id}`));setSummary('');setMessage('Scope revision saved; previous revisions retained.')})}}>
        <h3>Save a scope revision</h3><label htmlFor="change-summary">Change summary</label><textarea id="change-summary" required maxLength={2000} value={summary} onChange={e=>setSummary(e.target.value)}/>
        <label htmlFor="agreement">Agreement state</label><select id="agreement" value={agreement} onChange={e=>setAgreement(e.target.value)}><option value="proposed">Proposed</option><option value="agreed">Agreed</option><option value="superseded">Superseded</option></select>
        <label htmlFor="agreement-source">Agreement source</label><textarea id="agreement-source" required={agreement==='agreed'} value={source} maxLength={2000} onChange={e=>setSource(e.target.value)}/>
        <label htmlFor="revision-visibility">Revision visibility</label><select id="revision-visibility" value={revisionVisibility} onChange={e=>setRevisionVisibility(e.target.value)}><option value="private">Private</option>{detail.stream.visibility==='shared'&&<option value="shared">Shared · summary and saved scope will be visible</option>}</select>
        <button className="primary-button" disabled={busy}>Save scope revision</button></form>}
    </section>}
    <section className="foundation-panel portal-section"><h2>Scope revisions</h2>{detail.revisions.length?<ul>{detail.revisions.map(r=><li key={r.id}><button className="text-button" onClick={()=>setSelectedRevision(r)}>Revision {r.revision_number}: {r.change_summary}</button><p>{r.visibility} · {r.agreement_state} · {new Date(r.created_at).toLocaleString()}</p></li>)}</ul>:<p>No saved scope revisions yet.</p>}
      {selectedRevision&&<><h3>Revision {selectedRevision.revision_number} · read only</h3><ScopeSnapshot body={selectedRevision.body_json}/>{owner&&<><h3>Compare with current draft</h3><div className="table-scroll"><table><thead><tr><th>Field</th><th>Saved revision</th><th>Current draft</th></tr></thead><tbody>{fields.map(([key,label])=><tr key={key}><th>{label}</th><td><RichTextView value={String(JSON.parse(selectedRevision.body_json)[key]??'')} document={JSON.parse(selectedRevision.body_json).richText?.[key]}/></td><td><RichTextView value={scope[key]} document={scopeDocs[key]}/></td></tr>)}</tbody></table></div>{!detail.stream.archived_at&&<button className="outline-button" disabled={busy} onClick={()=>{if(discard())perform(async()=>{const old=JSON.parse(selectedRevision.body_json);await request(`/workstreams/${detail.stream.id}/draft`,'POST',{version:detail.draft?.version??0,scope:{...Object.fromEntries(fields.map(([key])=>[key,typeof old[key]==='string'?old[key]:''])),richText:old.richText??{}}});hydrate(await request(`/workstreams/${detail.stream.id}`));setMessage('Older scope copied into a new draft. Its saved revision is unchanged.')})}}>Copy revision into new draft</button>}</>}</>}
    </section></>}
    </div></div><p role="status" aria-live="polite">{message}</p></>
}
