import { useEffect,useState } from 'react'
import { RichTextEditor,RichTextView } from './RichText'
import { readRichText } from '../shared/rich-text'
import type { RichDocument } from '../shared/rich-text'
const states={open:'Not started',in_progress:'In progress',blocked:'Waiting',completed:'Done',cancelled:'Cancelled',draft:'Draft'}
type Item={id:string;title:string;details:string;details_doc_json:string|null;status:string;priority:number|null;assignee_name:string|null;due_date:string|null;visibility:string;version:number;completed_at:string|null;archived_at:string|null;overdue?:boolean}
type Revision={revision_number:number;body_json:string;created_at:string}
type Detail={item:Item;revisions?:Revision[];shareable?:boolean}
export function WorkstreamItems({workspaceId,workstreamId,role,preview,parentShared,parentArchived,onDirtyChange,onSaved}:{workspaceId:string;workstreamId:string;role:string;preview:boolean;parentShared:boolean;parentArchived:boolean;onDirtyChange:(dirty:boolean)=>void;onSaved:()=>void}) {
  const [items,setItems]=useState<Item[]>([]),[detail,setDetail]=useState<Detail|null>(null),[creating,setCreating]=useState(false),[dirty,setDirty]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
  const [query,setQuery]=useState(''),[state,setState]=useState(''),[contactFilter,setContactFilter]=useState(''),[archived,setArchived]=useState(false),[overdue,setOverdue]=useState(false),[hasMore,setHasMore]=useState(false)
  const [title,setTitle]=useState(''),[details,setDetails]=useState(''),[doc,setDoc]=useState<RichDocument|null>(null),[status,setStatus]=useState('open'),[priority,setPriority]=useState(''),[contact,setContact]=useState(''),[date,setDate]=useState('')
  const [conflict,setConflict]=useState(false),[latest,setLatest]=useState<Detail|null>(null),[sharing,setSharing]=useState<Detail|null>(null),[revision,setRevision]=useState<Revision|null>(null)
  const owner=role==='owner'&&!preview,editable=role!=='viewer'&&!preview&&!parentArchived
  const base=`/api/workspaces/${workspaceId}`
  const listPath=`/workstreams/${workstreamId}/items?${new URLSearchParams({status:state,q:query,owner:contactFilter,archived:archived?'1':'0',overdue:overdue?'1':'0',preview:preview?'1':'0'})}`
  async function request(path:string,method='GET',body?:object){const target=preview&&method==='GET'&&path.startsWith('/items/')&&!path.endsWith('/share-preview')?path+'?preview=1':path;const r=await fetch(base+target,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error??'Unable to save item.'),{status:r.status});if(method!=='GET')onSaved();return d}
  async function load(){const result=await request(listPath);setItems(result.items);setHasMore(result.hasMore)}
  useEffect(()=>{let current=true;request(listPath).then(d=>{if(current){setItems(d.items);setHasMore(d.hasMore)}}).catch(e=>{if(current)setMessage(e.message)});return()=>{current=false}},[listPath,workspaceId])
  useEffect(()=>{onDirtyChange(dirty)},[dirty,onDirtyChange])
  useEffect(()=>()=>onDirtyChange(false),[onDirtyChange])
  function discard(){return !dirty||window.confirm('Discard unsaved item changes?')}
  function hydrate(d:Detail){setDetail(d);setTitle(d.item.title);setDetails(d.item.details);setDoc(readRichText(d.item.details_doc_json,d.item.details));setStatus(d.item.status);setPriority(d.item.priority?.toString()??'');setContact(d.item.assignee_name??'');setDate(d.item.due_date??'');setDirty(false);setCreating(false);setConflict(false);setLatest(null);setSharing(null);setRevision(null)}
  async function perform(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();await load()}catch(e){setMessage((e as Error).message);if((e as Error&{status?:number}).status===409)setConflict(true)}finally{setBusy(false)}}
  const values={title,details,detailsDoc:doc,status,priority:priority?Number(priority):null,ownerName:contact||null,dueDate:date||null}
  const content=<><label htmlFor="item-title">Item title</label><input id="item-title" required maxLength={300} value={title} onChange={e=>{setTitle(e.target.value);setDirty(true)}}/>
    <label htmlFor="item-details">Item details</label><RichTextEditor key={`${detail?.item.id??'new'}:${detail?.item.version??0}`} id="item-details" label="Item details" value={details} document={doc} maxLength={20000} onDirty={()=>setDirty(true)} onChange={(text,json)=>{setDetails(text);setDoc(json);setDirty(true)}}/>
    <div className="item-form-grid"><div><label htmlFor="item-status">Item status</label><select id="item-status" value={status} onChange={e=>{setStatus(e.target.value);setDirty(true)}}>{Object.entries(states).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div>
    <div><label htmlFor="item-priority">Item priority</label><select id="item-priority" value={priority} onChange={e=>{setPriority(e.target.value);setDirty(true)}}><option value="">Not set</option>{[1,2,3,4,5].map(value=><option key={value}>{value}</option>)}</select></div>
    <div><label htmlFor="item-owner">Item owner or contact</label><input id="item-owner" maxLength={200} value={contact} onChange={e=>{setContact(e.target.value);setDirty(true)}}/></div>
    <div><label htmlFor="item-due">Item due date (optional)</label><input id="item-due" type="date" value={date} onChange={e=>{setDate(e.target.value);setDirty(true)}}/></div></div></>
  return <section id="workstream-items" className="foundation-panel portal-section"><h2>Items in this workstream</h2><p>Break the work into individual pieces. Each item has its own status; the overall workstream status stays separate.</p>
    {editable&&<button className="primary-button" disabled={busy} onClick={()=>{if(discard()){setDetail(null);setCreating(true);setTitle('');setDetails('');setDoc(null);setStatus('open');setPriority('');setContact('');setDate('');setDirty(false);setConflict(false);setLatest(null);setSharing(null);setRevision(null)}}}>Add item</button>}
    {parentArchived&&<p>Restore the workstream to add, edit or restore items.</p>}
    <div className="item-filters"><div><label htmlFor="item-search">Search items</label><input id="item-search" type="search" value={query} onChange={e=>setQuery(e.target.value)}/></div><div><label htmlFor="item-filter-status">Filter item status</label><select id="item-filter-status" value={state} onChange={e=>setState(e.target.value)}><option value="">All statuses</option>{Object.entries(states).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></div><div><label htmlFor="item-filter-owner">Filter item owner</label><input id="item-filter-owner" value={contactFilter} onChange={e=>setContactFilter(e.target.value)}/></div></div>
    <div className="portal-actions"><label className="inline-check"><input type="checkbox" checked={overdue} onChange={e=>setOverdue(e.target.checked)}/>Overdue items only</label>{owner&&<label className="inline-check"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)}/>Include archived items and parent</label>}</div>
    {items.length?<ul className="record-list item-list">{items.map(item=><li key={item.id}><button className="record-button" aria-current={detail?.item.id===item.id?'true':undefined} onClick={()=>{if(discard())perform(async()=>{hydrate(await request(`/items/${item.id}`))})}}>{item.title}</button><p>{states[item.status as keyof typeof states]} · {item.visibility}{item.archived_at?' · Archived':''}{item.overdue?' · Overdue':''}</p><p>{item.assignee_name??'Unassigned'} · {item.due_date?`Due ${item.due_date}`:'No due date'} · {item.priority?`Priority ${item.priority}`:'Priority not set'}</p></li>)}</ul>:<p>{query||state||contactFilter||overdue||archived?'No items match these filters.':preview||role==='viewer'?'No shared items in this workstream yet.':'No items yet. Add the first piece of work when you’re ready.'}</p>}
    {hasMore&&<p>Showing the first 200 matching items. Narrow the filters to find more.</p>}
    {(creating||detail)&&<div className="item-detail"><h3>{creating?'New item':detail!.item.title}</h3>
      {conflict&&<aside><h4>This item changed</h4><p>Your unsaved input is retained. Compare before reloading.</p>{detail&&<button className="outline-button" onClick={()=>perform(async()=>setLatest(await request(`/items/${detail.item.id}`)))}>Compare latest saved item</button>}{latest&&<><h4>Latest saved item</h4><p>{latest.item.title} · {states[latest.item.status as keyof typeof states]}</p><RichTextView value={latest.item.details} document={latest.item.details_doc_json}/><button className="outline-button" onClick={()=>{if(discard())hydrate(latest)}}>Reload latest saved item</button></>}</aside>}
      {editable&&(!detail?.item.archived_at)?<form onSubmit={e=>{e.preventDefault();perform(async()=>{const saved=creating?await request(`/workstreams/${workstreamId}/items`,'POST',{...values,visibility:owner?'private':'shared'}):await request(`/items/${detail!.item.id}`,'PATCH',{...values,version:detail!.item.version});hydrate(await request(`/items/${saved.item.id}`));setMessage(creating?(owner?'Item added privately; workstream status unchanged.':'Shared item added; workstream status unchanged.'):'Item saved; history retained.')})}}>{content}<button className="primary-button" disabled={busy}>{creating?'Create item':'Save item'}</button></form>:detail&&<><RichTextView value={detail.item.details} document={detail.item.details_doc_json}/><p>{states[detail.item.status as keyof typeof states]} · {detail.item.assignee_name??'Unassigned'}</p></>}
      {detail&&<><p>{detail.item.visibility==='private'?'Private item':'Shared item'}{detail.item.completed_at?` · Completed ${new Date(detail.item.completed_at).toLocaleString()}`:''}</p>{owner&&<div className="portal-actions"><button className="outline-button" disabled={busy||parentArchived} onClick={()=>{if(discard())perform(async()=>{const archivedNow=!detail.item.archived_at;await request(`/items/${detail.item.id}`,'PATCH',{version:detail.item.version,archived:archivedNow});hydrate(await request(`/items/${detail.item.id}`));setMessage(archivedNow?'Item archived; history retained.':'Item restored.')})}}>{detail.item.archived_at?'Restore item':'Archive item'}</button>
        {!detail.item.archived_at&&!parentArchived&&<button className="outline-button" disabled={busy} onClick={()=>{if(discard())perform(async()=>{if(detail.item.visibility==='shared'){await request(`/items/${detail.item.id}`,'PATCH',{version:detail.item.version,visibility:'private'});hydrate(await request(`/items/${detail.item.id}`));setMessage('Item is private.')}else setSharing(await request(`/items/${detail.item.id}/share-preview`))})}}>{detail.item.visibility==='shared'?'Make item private':'Preview item sharing'}</button>}</div>}
      {sharing&&<aside className="share-preview"><h4>Shared item preview</h4><p>{sharing.item.title} · {states[sharing.item.status as keyof typeof states]}</p><RichTextView value={sharing.item.details} document={sharing.item.details_doc_json}/><p>{sharing.item.assignee_name??'Unassigned'} · {sharing.item.due_date??'No due date'}</p><p>{sharing.item.priority?`Priority ${sharing.item.priority}`:'Priority not set'}</p><p>Current item text, status, priority, owner and date are shared. Edit history stays private.</p>{!sharing.shareable||!parentShared?<p>Share the workstream before sharing this item.</p>:<button className="primary-button" disabled={busy} onClick={()=>perform(async()=>{await request(`/items/${detail.item.id}`,'PATCH',{version:detail.item.version,visibility:'shared'});hydrate(await request(`/items/${detail.item.id}`));setMessage('Item shared with active members.')})}>Share this item</button>}</aside>}
      {owner&&<section><h4>Item history · private</h4>{detail.revisions?.map(r=><div key={r.revision_number}><button className="text-button" onClick={()=>setRevision(r)}>View item version {r.revision_number}</button><span> · {new Date(r.created_at).toLocaleString()}</span></div>)}{revision&&<><h4>Item version {revision.revision_number} · read only</h4><p>{JSON.parse(revision.body_json).title} · {states[JSON.parse(revision.body_json).status as keyof typeof states]}</p><RichTextView value={JSON.parse(revision.body_json).details} document={JSON.parse(revision.body_json).detailsDoc}/><p>{JSON.parse(revision.body_json).ownerName??'Unassigned'} · {JSON.parse(revision.body_json).dueDate??'No due date'}</p></>}</section>}</>}
      <button className="text-button" onClick={()=>{if(discard()){setDetail(null);setCreating(false);setDirty(false);setSharing(null);setRevision(null);setConflict(false)}}}>Close item</button>
    </div>}<p role="status" aria-live="polite">{message}</p>
  </section>
}
